name: Publish to Buildkite
on:
 workflow_call:
   inputs:
     version:
       description: SourceGit package version
       required: true
       type: string
   secrets:
     BUILDKITE_TOKEN:
       required: true
jobs:
 publish:
   name: Publish to Buildkite
   runs-on: ubuntu-latest
   strategy:
     matrix:
       runtime: [linux-x64, linux-arm64]
   steps:
     - name: Download package artifacts
       uses: actions/download-artifact@v4
       with:
         name: package.${{ matrix.runtime }}
         path: packages

     - name: Publish DEB package
       env:
         BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
       run: |
         FILE=$(echo *.deb)
         curl -X POST https://api.buildkite.com/v2/packages/organizations/stone-w4tch3r/registries/sourcegit-fork-test-deb/packages \
           -H "Authorization: Bearer $BUILDKITE_TOKEN" \
           -F "file=@$FILE"

     - name: Publish RPM package
       env:
         BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
       run: |
         FILE=$(echo *.rpm)
         curl -X POST https://api.buildkite.com/v2/packages/organizations/stone-w4tch3r/registries/sourcegit-fork-test-rpm/packages \
           -H "Authorization: Bearer $BUILDKITE_TOKEN" \
           -F "file=@$FILE"
